/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test.pb-c.h"
void   network_message__init
                     (NetworkMessage         *message)
{
  static const NetworkMessage init_value = NETWORK_MESSAGE__INIT;
  *message = init_value;
}
size_t network_message__get_packed_size
                     (const NetworkMessage *message)
{
  assert(message->base.descriptor == &network_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t network_message__pack
                     (const NetworkMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &network_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t network_message__pack_to_buffer
                     (const NetworkMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &network_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetworkMessage *
       network_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetworkMessage *)
     protobuf_c_message_unpack (&network_message__descriptor,
                                allocator, len, data);
}
void   network_message__free_unpacked
                     (NetworkMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &network_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor network_message__field_descriptors[5] =
{
  {
    "packet_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NetworkMessage, packet_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol_version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NetworkMessage, protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NetworkMessage, server_ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_port",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NetworkMessage, server_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_state_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NetworkMessage, next_state_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned network_message__field_indices_by_name[] = {
  4,   /* field[4] = next_state_id */
  0,   /* field[0] = packet_id */
  1,   /* field[1] = protocol_version */
  2,   /* field[2] = server_ip */
  3,   /* field[3] = server_port */
};
static const ProtobufCIntRange network_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor network_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetworkMessage",
  "NetworkMessage",
  "NetworkMessage",
  "",
  sizeof(NetworkMessage),
  5,
  network_message__field_descriptors,
  network_message__field_indices_by_name,
  1,  network_message__number_ranges,
  (ProtobufCMessageInit) network_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
